In [48]:
import os
import os.path
from glob import iglob
import re

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [51]:
parameter_names = ['side', 'ahead', 'behind', 'iterations', 'layers', 'layer_size']

In [62]:
acc = []
for path in iglob('data/grid_search/*.log'):
    n = os.path.basename(path)
    parameters = list(map(int, n.replace('.log', '').split('_')))
    with open(path, 'rt') as fp:
        log = fp.read()
    m = re.search('MPH ([\d.]+)', log)
    if not m:
        continue
    mph = float(m.group(1))
    acc.append(parameters + [mph])
data = pd.DataFrame(acc, columns=parameter_names + ['trial', 'speed'])

In [63]:
data.sort_values('speed', ascending=False)

    side  ahead  behind  iterations  layers  layer_size  trial  speed
22     1      5       0      100000       1         200      1  71.92
8      1     10       2      100000       1         100      0  71.90
10     1     10       2      100000       1          50      0  71.85
13     1     10       2      100000       3          50      0  71.78
4      1     10       0      100000       2          50      0  71.78
12     1     10       2      100000       2          50      0  71.65
74     1      5       2      100000       2         100      0  71.62
3      1     10       0      100000       2         100      0  71.58
5      1     10       0      100000       3         100      0  71.54
14     1     10       2      100000       4          50      0  71.52
38     1      5       0      100000       3         100      2  71.52
7      1     10       0      100000       4          50      0  71.44
0      1     10       0      100000       1         100      0  71.42
21     1      5       0      100000       1         200      0  71.38
17     1     15       0      100000       2          50      0  71.36
26     1      5       0      100000       1          50      2  71.33
9      1     10       2      100000       1         200      0  71.26
75     1      5       2      100000       2          50      0  71.25
73     1      5       2      100000       1          50      0  71.23
29     1      5       0      100000       2         100      2  71.23
25     1      5       0      100000       1          50      1  71.20
43     1      5       0      100000       4          50      0  71.17
72     1      5       2      100000       1         200      0  71.16
30     1      5       0      100000       2         200      0  71.15
6      1     10       0      100000       3          50      0  71.14
77     1      5       2      100000       3          50      0  71.14
18     1      5       0      100000       1         100      0  71.10
16     1     15       0      100000       1          50      0  71.10
41     1      5       0      100000       3          50      2  71.08
11     1     10       2      100000       2         100      0  71.07
..   ...    ...     ...         ...     ...         ...    ...    ...
94     1      5       2       10000       2          50      0  69.36
85     1      5       2       10000       1          50      0  69.24
52     1      5       0       10000       1          50      2  69.16
66     1      5       0       10000       3         200      1  69.11
49     1      5       0       10000       1         200      2  69.07
63     1      5       0       10000       3         100      1  68.97
96     1      5       2       10000       2          50      2  68.95
88     1      5       2       10000       2         100      0  68.93
95     1      5       2       10000       2          50      1  68.86
86     1      5       2       10000       1          50      1  68.80
97     1      5       2       10000       3          50      0  68.79
69     1      5       0       10000       3          50      1  68.64
59     1      5       0       10000       2          50      0  68.56
60     1      5       0       10000       2          50      1  68.38
54     1      5       0       10000       2         100      1  68.36
50     1      5       0       10000       1          50      0  68.33
90     1      5       2       10000       2         100      2  68.32
62     1      5       0       10000       3         100      0  68.16
61     1      5       0       10000       2          50      2  68.16
47     1      5       0       10000       1         200      0  68.13
68     1      5       0       10000       3          50      0  68.00
58     1      5       0       10000       2         200      2  67.55
53     1      5       0       10000       2         100      0  67.52
57     1      5       0       10000       2         200      1  67.50
56     1      5       0       10000       2         200      0  67.42
44     1      5       0       10000       1         100      0  67.26
51     1      5       0       10000       1          50      1  66.58
64     1      5       0       10000       3         100      2  66.16
46     1      5       0       10000       1         100      2  66.08
48     1      5       0       10000       1         200      1  63.40

[100 rows x 8 columns]

In [64]:
stat_data = data.groupby(parameter_names)['speed'].describe().reset_index()
stat_data = stat_data.sort_values('mean', ascending=False)
stat_data

,side,ahead,behind,iterations,layers,layer_size,count,mean,std,min,25%,50%,75%,max
43,1,10,2,100000,1,100,1.0,71.900000,NaN,71.90,71.900,71.90,71.900,71.90
42,1,10,2,100000,1,50,1.0,71.850000,NaN,71.85,71.850,71.85,71.850,71.85
47,1,10,2,100000,3,50,1.0,71.780000,NaN,71.78,71.780,71.78,71.780,71.78
37,1,10,0,100000,2,50,1.0,71.780000,NaN,71.78,71.780,71.78,71.780,71.78
45,1,10,2,100000,2,50,1.0,71.650000,NaN,71.65,71.650,71.65,71.650,71.65
30,1,5,2,100000,2,100,1.0,71.620000,NaN,71.62,71.620,71.62,71.620,71.62
38,1,10,0,100000,2,100,1.0,71.580000,NaN,71.58,71.580,71.58,71.580,71.58
40,1,10,0,100000,3,100,1.0,71.540000,NaN,71.54,71.540,71.54,71.540,71.54
48,1,10,2,100000,4,50,1.0,71.520000,NaN,71.52,71.520,71.52,71.520,71.52
41,1,10,0,100000,4,50,1.0,71.440000,NaN,71.44,71.440,71.44,71.440,71.44
35,1,10,0,100000,1,100,1.0,71.420000,NaN,71.42,71.420,71.42,71.420,71.42
51,1,15,0,100000,2,50,1.0,71.360000,NaN,71.36,71.360,71.36,71.360,71.36
44,1,10,2,100000,1,200,1.0,71.260000,NaN,71.26,71.260,71.26,71.260,71.26
29,1,5,2,100000,2,50,1.0,71.250000,NaN,71.25,71.250,71.25,71.250,71.25
26,1,5,2,100000,1,50,1.0,71.230000,NaN,71.23,71.230,71.23,71.230,71.23
16,1,5,0,100000,3,100,3.0,71.203333,0.274651,71.03,71.045,71.06,71.290,71.52
17,1,5,0,100000,4,50,1.0,71.170000,NaN,71.17,71.170,71.17,71.170,71.17
28,1,5,2,100000,1,200,1.0,71.160000,NaN,71.16,71.160,71.16,71.160,71.16
39,1,10,0,100000,3,50,1.0,71.140000,NaN,71.14,71.140,71.14,71.140,71.14
31,1,5,2,100000,3,50,1.0,71.140000,NaN,71.14,71.140,71.14,71.140,71.14
49,1,15,0,100000,1,50,1.0,71.100000,NaN,71.10,71.100,71.10,71.100,71.10
46,1,10,2,100000,2,100,1.0,71.070000,NaN,71.07,71.070,71.07,71.070,71.07
32,1,5,2,100000,3,100,1.0,70.960000,NaN,70.96,70.960,70.96,70.960,70.96
9,1,5,0,100000,1,50,3.0,70.943333,0.560922,70.30,70.750,71.20,71.265,71.33
27,1,5,2,100000,1,100,1.0,70.920000,NaN,70.92,70.920,70.92,70.920,70.92
50,1,15,0,100000,1,100,1.0,70.920000,NaN,70.92,70.920,70.92,70.920,70.92
11,1,5,0,100000,1,200,3.0,70.913333,1.304198,69.44,70.410,71.38,71.650,71.92
34,1,10,0,100000,1,50,1.0,70.910000,NaN,70.91,70.910,70.91,70.910,70.91
33,1,5,2,100000,4,50,1.0,70.900000,NaN,70.90,70.900,70.90,70.900,70.90
14,1,5,0,100000,2,200,3.0,70.866667,0.368556,70.45,70.725,71.00,71.075,71.15
13,1,5,0,100000,2,100,3.0,70.866667,0.331713,70.58,70.685,70.79,71.010,71.23
10,1,5,0,100000,1,100,3.0,70.833333,0.238607,70.64,70.700,70.76,70.930,71.10
12,1,5,0,100000,2,50,3.0,70.730000,0.399500,70.27,70.600,70.93,70.960,70.99
15,1,5,0,100000,3,50,3.0,70.683333,0.472899,70.16,70.485,70.81,70.945,71.08
36,1,10,0,100000,1,200,1.0,70.370000,NaN,70.37,70.370,70.37,70.370,70.37
20,1,5,2,10000,1,100,3.0,70.103333,0.481698,69.60,69.875,70.15,70.355,70.56
18,1,5,0,100000,4,100,1.0,69.990000,NaN,69.99,69.990,69.99,69.990,69.99
21,1,5,2,10000,1,200,3.0,69.863333,0.173877,69.73,69.765,69.80,69.930,70.06
24,1,5,2,10000,2,200,3.0,69.853333,0.452364,69.49,69.600,69.71,70.035,70.36
8,1,5,0,10000,3,200,3.0,69.593333,0.466083,69.11,69.370,69.63,69.835,70.04
25,1,5,2,10000,3,50,3.0,69.526667,0.638462,68.79,69.330,69.87,69.895,69.92
19,1,5,2,10000,1,50,3.0,69.286667,0.511599,68.80,69.020,69.24,69.530,69.82
22,1,5,2,10000,2,50,3.0,69.056667,0.266521,68.86,68.905,68.95,69.155,69.36
23,1,5,2,10000,2,100,3.0,68.976667,0.681200,68.32,68.625,68.93,69.305,69.68
6,1,5,0,10000,3,50,3.0,68.753333,0.815925,68.00,68.320,68.64,69.130,69.62
4,1,5,0,10000,2,100,3.0,68.536667,1.115542,67.52,67.940,68.36,69.045,69.73
3,1,5,0,10000,2,50,3.0,68.366667,0.200333,68.16,68.270,68.38,68.470,68.56
0,1,5,0,10000,1,50,3.0,68.023333,1.317055,66.58,67.455,68.33,68.745,69.16
7,1,5,0,10000,3,100,3.0,67.763333,1.446386,66.16,67.160,68.16,68.565,68.97
1,1,5,0,10000,1,100,3.0,67.620000,1.748027,66.08,66.670,67.26,68.390,69.52
5,1,5,0,10000,2,200,3.0,67.490000,0.065574,67.42,67.460,67.50,67.525,67.55
2,1,5,0,10000,1,200,3.0,66.866667,3.038788,63.40,65.765,68.13,68.600,69.07